from .views import *
from django.urls import path 
urlpatterns = [
    path('', home, name='home'),
     path('category/<str:foo>/', category, name='category'),
     path('category/<str:foo>/filter-products/', filter_products, name='filter_products'),
     path('AllCategory/', AllCategory, name='AllCategory'),
    path('product/<int:pk>/', product, name='product'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_user, name='logout'),
    path('verified/', check_email_verification, name='verification_success'),
    path('restPassword/', restPassword, name='restPassword'),
    path('forgot-password/', forgot_password, name='forgot_password'),
    path('password_reset_callback/', password_reset_callback, name='password_reset_callback'),
    path('search/', search, name='search'),
    path('post_deal/', post_deal, name='post_deal'),
    path("user_profile/<int:identifier>/", user_profile, name="user_profile"),
    path("follow/<int:user_id>/", follow, name="follow"),
    path("unfollow/<int:user_id>/", unfollow, name="unfollow"),
    path('wishlist/', wishlist, name='wishlist'),
    path('like/<int:product_id>/', like_product, name='like_product'),
    path('settings/', settings, name='settings'),
    path('settings/update_info/', update_info, name='update_info'),
    path('product/<int:product_id>/toggle-save/', toggle_save_product, name='toggle_save_product'),
    path('saved-items/', saved_items, name='saved_items'),
    path('inbox/', inbox, name='inbox'),
    path('send_message/', send_message, name='send_message'),

]
