# Generated by Django 5.1.6 on 2025-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
