# Generated by Django 5.1.6 on 2025-02-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0003_product_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='view_count',
            new_name='views',
        ),
    ]
