# Generated by Django 5.1.6 on 2025-02-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0004_rename_view_count_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.CharField(default=' ', max_length=5000),
        ),
    ]
