# Generated by Django 5.1.6 on 2025-02-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0005_product_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(default='[]'),
        ),
    ]
