# Generated by Django 5.1.7 on 2025-03-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0011_firebaseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
