# Generated by Django 5.1.7 on 2025-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0013_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='saved_products',
            field=models.ManyToManyField(blank=True, related_name='saved_by_customers', to='waffrli.product'),
        ),
    ]
