# Generated by Django 5.1.7 on 2025-03-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0016_message_is_reply_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
