# Generated by Django 5.1.7 on 2025-03-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0017_message_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_starred',
        ),
    ]
