# Generated by Django 5.1.7 on 2025-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0018_remove_message_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='City',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
