# Generated by Django 5.1.7 on 2025-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0019_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(max_length=55),
        ),
    ]
