# Generated by Django 5.1.7 on 2025-03-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0021_wishlistitem_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='notify_website',
        ),
    ]
