# Generated by Django 5.1.7 on 2025-04-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0023_customer_formatted_address_customer_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
