# Generated by Django 5.1.7 on 2025-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0024_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
