# Generated by Django 5.1.7 on 2025-04-14 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0025_product_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_price', 'Price'], name='waffrli_pro_sale_pr_afe678_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['views', '-create_at'], name='waffrli_pro_views_548809_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'city', 'brand'], name='waffrli_pro_store_48d9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sale_price'], name='waffrli_pro_categor_bb432f_idx'),
        ),
    ]
