# Generated by Django 5.1.7 on 2025-04-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0026_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='City',
        ),
    ]
