# Generated by Django 5.1.7 on 2025-04-16 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0027_remove_customer_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store_type',
            field=models.CharField(choices=[('online', 'Online Store'), ('physical', 'Physical Store')], default='online', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store_type'], name='waffrli_pro_store_t_f13e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['latitude', 'longitude'], name='waffrli_pro_latitud_5780bd_idx'),
        ),
    ]
