# Generated by Django 5.1.7 on 2025-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0028_product_formatted_address_product_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
