# Generated by Django 5.1.7 on 2025-04-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0029_product_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spam', 'Spam'), ('repost', 'Repost'), ('troll', 'Troll'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the report')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected'), ('resolved', 'Issue Resolved')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='waffrli.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_deals', to='waffrli.customer')),
            ],
            options={
                'verbose_name': 'Reported Deal',
                'verbose_name_plural': 'Reported Deals',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'reporter', 'reason')},
            },
        ),
    ]
