# Generated by Django 5.1.7 on 2025-05-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0032_alter_message_options_message_for_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseUser',
        ),
    ]
