# Generated by Django 5.1.7 on 2025-05-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0033_delete_firebaseuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Dealurl',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
