# Generated by Django 5.1.7 on 2025-05-12 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0034_alter_product_dealurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bad_votes',
            field=models.ManyToManyField(blank=True, related_name='bad_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='community_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='good_votes',
            field=models.ManyToManyField(blank=True, related_name='good_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
