# Generated by Django 5.1.7 on 2025-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0035_product_bad_votes_product_community_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\img\\CustomerPics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\img\\ProductPics'),
        ),
    ]
