# Generated by Django 5.1.7 on 2025-05-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0036_alter_customer_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bad_votes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='community_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='good_votes',
        ),
    ]
