# Generated by Django 5.1.7 on 2025-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0040_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\img\\ProductPics'),
        ),
    ]
