# Generated by Django 5.1.6 on 2025-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffrli', '0042_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/CustomerPics'),
        ),
    ]
